# OpenTelemetry Collector Configuration - Local Development
# This config receives OTLP from Elava and exports to Prometheus, Loki, and Jaeger

receivers:
  # OTLP receiver - accepts telemetry from Elava
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  # Batch processor - groups telemetry for efficiency
  batch:
    timeout: 10s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Resource processor - adds service metadata
  resource:
    attributes:
      - key: service.name
        value: elava
        action: upsert
      - key: deployment.environment
        value: local
        action: upsert

  # Memory limiter - prevents OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

exporters:
  # Prometheus exporter - exposes metrics for scraping
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: elava
    const_labels:
      environment: local
    resource_to_telemetry_conversion:
      enabled: true

  # Loki exporter - sends logs/span events
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      resource:
        service.name: "service_name"
        deployment.environment: "deployment_environment"
      attributes:
        severity: "severity"
        resource.type: "resource_type"
        change.type: "change_type"

  # OTLP exporter to Jaeger - sends traces
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Debug exporter - logs telemetry to console
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  # Health check endpoint
  health_check:
    endpoint: 0.0.0.0:13133

  # pprof for profiling
  pprof:
    endpoint: 0.0.0.0:1777

  # zpages for diagnostics
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]

  pipelines:
    # Traces pipeline
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [otlp/jaeger, debug]

    # Metrics pipeline
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [prometheus, debug]

    # Logs pipeline (for span events)
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [loki, debug]

  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888
