# Prometheus Configuration - Local Development

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'local'
    cluster: 'dev'

# Scrape configs
scrape_configs:
  # Scrape OTEL Collector metrics endpoint
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          service: 'elava'

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape collector's own telemetry
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'
