linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gocyclo
    - gocognit
    - bodyclose
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 20
  funlen:
    lines: 50
    statements: 30

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    # Legacy code with complexity issues - will refactor later
    - "providers/aws/.*"
    - "cmd/elava/scan.go"
    - "cmd/elava/otel_init.go"
    - "telemetry/otel.go"
    - "storage/mvcc_test.go"