# golangci-lint configuration for elava
run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gocyclo
    - gocognit
    - bodyclose
    - gosec
    - funlen

linters-settings:
  gocyclo:
    min-complexity: 10
  gocognit:
    min-complexity: 20
  funlen:
    lines: 50
    statements: 30

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0