# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: elava

before:
  hooks:
    - go mod tidy
    - go fmt ./...
    - go vet ./...

builds:
  - id: elava
    main: ./cmd/elava
    binary: elava
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: elava
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"

dockers:
  - image_templates:
      - "ghcr.io/yairfalse/elava:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=COMMIT={{ .Commit }}"
      - "--build-arg=DATE={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - image_templates:
      - "ghcr.io/yairfalse/elava:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=COMMIT={{ .Commit }}"
      - "--build-arg=DATE={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/yairfalse/elava:{{ .Version }}"
    image_templates:
      - "ghcr.io/yairfalse/elava:{{ .Version }}-amd64"
      - "ghcr.io/yairfalse/elava:{{ .Version }}-arm64"
  - name_template: "ghcr.io/yairfalse/elava:latest"
    image_templates:
      - "ghcr.io/yairfalse/elava:{{ .Version }}-amd64"
      - "ghcr.io/yairfalse/elava:{{ .Version }}-arm64"

release:
  github:
    owner: yairfalse
    name: elava
  draft: false
  prerelease: auto
